### ISSUE TITLE
Unable to connect to several datasources

### ISSUE THREAD

**Issue by futuarmo** [HadesArchitect/GrafanaCassandraDatasource#96] opened 2021-03-03 16:16 UTC
Looks like we have only one instance of backend for all added to Grafana datasources, so we need to keep information about all connections.

Reproducing: configure instance of plugin, press test and then try to test connection to another source. The result will be the same with the previous attempt

**Comment by HadesArchitect** [comment] 2021-03-03 19:48
Looks like a big fat critical issue indeed.

**Comment by bacsog** [comment] 2021-04-05 09:03
Just came across this as well. Lost 2 hours of easter holiday on it. After having successfully validated one connection, any subsequent change is accepted as correct, but does not change any value for real. Only a Grafana restart solves the problem.

**Comment by HadesArchitect** [comment] 2021-04-06 17:46
@futuarmo The issue mentioned by @bacsog is of a different kind (not fixed by #99) Do you think we need a new ticket for that?

**Comment by bacsog** [comment] 2021-04-06 17:54
Ok, in this case let me add some more info. To reproduce:
- Add a new Cassandra datasource (supply valid values)
- Hit Save&Test: works
- create a panel using this datasource: works as well
- go back and change any value (IP: asdfasdfasdf, keyspace non-existent, etc)
- Hit Save&Test: still works (SHOULD NOT)
- test your previously created panel: still works (SHOULD NOT)

The only way I found to have new values picked up is a Grafana restart. We had our testDB connection "burnt into" Grafana.

**Comment by futuarmo** [comment] 2021-04-06 18:15
> 
> 
> @futuarmo The issue mentioned by @bacsog is of a different kind (not fixed by #99) Do you think we need a new ticket for that?

Yes, I think we need a new task. We store our connection settings, but for datasource Hit & test now we should remove cached connection

**Comment by HadesArchitect** [comment] 2021-04-06 19:02
Afaik connection query (save&test) has a special flag, that must be very easy to check and recreate connection. Let me check...

**Closed** 2021-05-08 19:59 UTC
Labels: backend, bug, critical
