### ISSUE TITLE
Metric Request Error

### ISSUE THREAD

**Issue by danielRV7** [HadesArchitect/GrafanaCassandraDatasource#113] opened 2021-07-28 09:16 UTC
Hey!

I just installed this plugin on my Grafana installation. When I want to connect it to my Cassandra cluster, it fails, saying "metric request error". The fields are correct (i'm almost 100% sure).

Should I do something in Cassandra config before trying to connect those two tools? Thanks in advance.

**Comment by JavadHosseini** [comment] 2021-07-30 12:17
I had the same problem but I found out my grafana version is 8 which is not supported by this plugin, what is your grafana version?

**Comment by SummaCumWilly** [comment] 2021-08-02 17:54
I, too, had the same issue. The version of Grafana I have is 8.0.5 and I'm running 4.0 RC1 Cassandra. I get the same errors. The log message that shows when Grafana is restarted is
`t=2021-08-02T11:19:41-0400 lvl=eror msg="Failed to start plugin" logger=plugins.backend pluginId=hadesarchitect-cassandra-datasource error="Incompatible API version with plugin. Plugin version: 1, Client versions: [2]"`
and then lots of `error='plugin unavailable'` every time I try to connect.

**Comment by annelaurefroment** [comment] 2021-08-03 02:46
From this error message, it looks like the plugin is using an older version of the Grafana backend plugin API which was deprecated in 7.0, and subsequently removed in 8.0. 
You can find more information about this in this github issue:
https://github.com/grafana/grafana/issues/33959

**Comment by futuarmo** [comment] 2021-08-03 05:35
Hello everyone!  Thanks for the reports. We are working to move plugin to new Grafana plugin API, so problem will be fixed. But now please use older version of Grafana

**Comment by HadesArchitect** [comment] 2021-09-08 15:42
Sure! What's the table structure? You can get it with `describe table NAME;` command

**Comment by danielRV7** [comment] 2021-09-09 09:01
> Sure! What's the table structure? You can get it with `describe table NAME;` command

CREATE TABLE gasp.surrogates (
    id timeuuid,
    plate text,
    ts timestamp,
    key text,
    value text,
    PRIMARY KEY ((id, plate), ts)
) WITH CLUSTERING ORDER BY (ts DESC)
    AND additional_write_policy = '99p'
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND cdc = false
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '16', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND default_time_to_live = 0
    AND extensions = {}
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair = 'BLOCKING'
    AND speculative_retry = '99p';

**Comment by danielRV7** [comment] 2021-09-17 08:46
> Sure! What's the table structure? You can get it with `describe table NAME;` command

Any idea about the structure I posted? :S

**Comment by HadesArchitect** [comment] 2021-09-20 18:28
Hey @danielRV7 I have an idea about that, can try to test it and get back to you tomorrow.

**Comment by danielRV7** [comment] 2021-09-21 10:39
> Hey @danielRV7 I have an idea about that, can try to test it and get back to you tomorrow.

Hey! Thank you so much 😁👌🏻

**Comment by danielRV7** [comment] 2021-09-22 09:07
> So, I see what's the problem, I'll get back with a solution in the next couple of days. Question: do you specify both ID and plate in your query (all the parts of the partition key?)

Thanks!! I think that yes, I am completing the query like this (but I have tested a lot of combinations but never saw data):

![photo_2021-09-22_11-07-16](https://user-images.githubusercontent.com/27138015/134315597-bdde3354-4d75-40f0-8858-ebf1e46d1a14.jpg)

**Comment by danielRV7** [comment] 2021-09-30 14:27
> So, I see what's the problem, I'll get back with a solution in the next couple of days. Question: do you specify both ID and plate in your query (all the parts of the partition key?)

My last photo was useful to you?

**Comment by HadesArchitect** [comment] 2021-09-30 15:42
Yes, absolutely. For this case, I'd suggest using the query editor, not the configurator. Please refer to https://github.com/HadesArchitect/GrafanaCassandraDatasource/wiki/User-Guide#query-editor I'll try to help you with the query later today.

**Comment by danielRV7** [comment] 2021-10-19 10:13
> Yes, absolutely. For this case, I'd suggest using the query editor, not the configurator. Please refer to https://github.com/HadesArchitect/GrafanaCassandraDatasource/wiki/User-Guide#query-editor I'll try to help you with the query later today.

Hey Hades, any tip about my query? I tried some times more but no success.

**Comment by HadesArchitect** [comment] 2021-12-12 19:27
Hey Daniel, please let me know which grafana version do you use atm?

**Comment by danielRV7** [comment] 2021-12-13 10:12
> Hey Daniel, please let me know which grafana version do you use atm?

Hi! I am using v7.1.3 (5723d951af)

**Comment by HadesArchitect** [comment] 2021-12-13 10:43
Thanks @danielRV7, that helps. I'll reproduce it today and check the case using that version. Will you be available for a quick call tomorrow or on Thursday if I couldn't make this work?

**Comment by danielRV7** [comment] 2021-12-13 10:46
> Thanks @danielRV7, that helps. I'll reproduce it today and check the case using that version. Will you be available for a quick call tomorrow or on Thursday if I couldn't make this work?

Sure, no problem, just mail me and we can schedule a call if you can't make it work. Anyway I think you will, probably my fault is a simple query composition mistake.

**Comment by danielRV7** [comment] 2022-01-25 15:01
> Thanks @danielRV7, that helps. I'll reproduce it today and check the case using that version. Will you be available for a quick call tomorrow or on Thursday if I couldn't make this work?

Hey Hades, did you managed to recreate the problem I had?

**Comment by futuarmo** [comment] 2022-02-26 09:24
Hello @danielRV7. Please try our new v2 RC3 version and give feedback

**Comment by HadesArchitect** [comment] 2022-04-28 08:59
@danielRV7 Did you manage to run this? If not, please schedule a call for next week: https://calendly.com/aleks-volochnev

**Comment by HadesArchitect** [comment] 2022-05-02 17:39
Hey there, I'm closing the issue, please feel free to reopen if it's still the case.

**Closed by HadesArchitect** 2022-05-02 17:39 UTC
